### ISSUE TITLE
First suggestion!

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-continuous-integration#1]
In the past we've discussed recommending GitHub Teams be set up for LSSTDESC repositories: one for admin access and another for developers granting write access. That allows easier maintenance over the long term. Given that this repo may serve as an example for others - it's an opportunity to do just that here and then note that on the README so people know who to contact if they wish to contribute.
Our format for Team names has been:  <repoName>-admins and <repoName>-developers.

**Comment by heather999** [comment]
I've gone ahead and done this - adding the Computing Coordinator Team and Computing WG conveners as "developers".  Others can and should feel free to ask for this elevated access. We should update the README to let people know how to reach out.

**Comment by stuartmcalpine** [comment]
Good suggestion, I have added a note to the readme!

**Comment by heather999** [comment]
Think this is done
